# Generated by Django 5.2.6 on 2025-10-13 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_code",
                    models.PositiveSmallIntegerField(db_index=True, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("temp", "温度"), ("hum", "湿度"), ("light", "光照")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=50)),
                ("unit", models.CharField(blank=True, default="", max_length=10)),
                ("latest_value", models.FloatField(blank=True, null=True)),
                ("latest_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="Sensor.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sensor", "created_at"],
                        name="Sensor_read_sensor__b96df0_idx",
                    )
                ],
            },
        ),
    ]
